apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vso-restart-workloads
  namespace: observability
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vso-restart-workloads
  namespace: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vso-restart-workloads
subjects:
  - kind: ServiceAccount
    name: vault-secrets-operator-controller-manager
    namespace: vault-secrets-operator-system
