apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: otel-client-tls
  namespace: observability
spec:
  vaultAuthRef: vso-auth
  mount: secret
  type: kv-v2
  path: observability/client-tls
  refreshAfter: 60s
  destination:
    name: otel-client-tls
    create: true
    overwrite: true
    labels:
      app.kubernetes.io/part-of: federated-observability
      app.kubernetes.io/managed-by: vault-secrets-operator
    transformation:
      excludeRaw: true
      excludes:
        - ca_crt
        - tls_crt
        - tls_key
      templates:
        ca.crt:
          text: '{{ get .Secrets "ca_crt" }}'
        tls.crt:
          text: '{{ get .Secrets "tls_crt" }}'
        tls.key:
          text: '{{ get .Secrets "tls_key" }}'
  rolloutRestartTargets:
    - kind: DaemonSet
      name: otel-agent
    - kind: Deployment
      name: otel-scraper
