apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hub-client-tls
  namespace: observability
spec:
  vaultAuthRef: vso-auth
  mount: observability
  type: kv-v2
  path: edge-certs/fed-observability-remote
  refreshAfter: 60s
  destination:
    name: otel-client-tls
    create: true
    overwrite: true
    labels:
      app.kubernetes.io/part-of: federated-observability
      app.kubernetes.io/managed-by: vault-secrets-operator
    transformation:
      excludeRaw: true
      excludes:
        - tls_crt
        - tls_key
        - ca_crt
      templates:
        tls.crt:
          text: '{{ get .Secrets "tls_crt" }}'
        tls.key:
          text: '{{ get .Secrets "tls_key" }}'
        ca.crt:
          text: '{{ get .Secrets "ca_crt" }}'
  rolloutRestartTargets:
    - kind: DaemonSet
      name: otel-agent
    - kind: Deployment
      name: otel-scraper
