apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  vaultAuthRef: vso-auth
  mount: observability
  type: kv-v2
  path: grafana-tls
  refreshAfter: 60s
  destination:
    name: grafana-tls
    create: true
    overwrite: true
    type: kubernetes.io/tls
    labels:
      app.kubernetes.io/part-of: federated-observability
      app.kubernetes.io/managed-by: vault-secrets-operator
    transformation:
      excludeRaw: true
      excludes:
        - tls_crt
        - tls_key
      templates:
        tls.crt:
          text: '{{ get .Secrets "tls_crt" }}'
        tls.key:
          text: '{{ get .Secrets "tls_key" }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: grafana
