apiVersion: v1
kind: ServiceAccount
metadata:
  name: vso-auth
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: federated-observability
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-auth
  namespace: monitoring
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso
    serviceAccount: vso-auth
