apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otel-aggregator
  namespace: observability
  labels:
    app.kubernetes.io/name: otel-aggregator
    app.kubernetes.io/part-of: federated-observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-aggregator
