apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-aggregator
  namespace: observability
  labels:
    app.kubernetes.io/name: otel-aggregator
    app.kubernetes.io/part-of: federated-observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-aggregator
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
