apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: observability-hub
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: federated-observability
spec:
  serviceName: redpanda
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: redpanda
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redpanda
        app.kubernetes.io/component: storage
    spec:
      securityContext:
        fsGroup: 101
        runAsUser: 101
        runAsGroup: 101
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: redpanda
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v24.1.1
          args:
            - redpanda
            - start
            - --smp=2
            - --memory=4G
            - --reserve-memory=1G
            - --default-log-level=info
            - --advertise-rpc-addr=$(POD_NAME).redpanda.observability-hub.svc.cluster.local:33145
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
            - name: kafka-tls
              containerPort: 9093
              protocol: TCP
            - name: rpc
              containerPort: 33145
              protocol: TCP
            - name: admin
              containerPort: 9644
              protocol: TCP
          resources:
            requests:
              cpu: "2"
              memory: 5Gi
            limits:
              cpu: "4"
              memory: 6Gi
          volumeMounts:
            - name: data
              mountPath: /var/lib/redpanda/data
            - name: config
              mountPath: /etc/redpanda
            - name: certs
              mountPath: /certs
              readOnly: true
          livenessProbe:
            httpGet:
              path: /v1/status/ready
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/status/ready
              port: admin
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: redpanda-config
        - name: certs
          secret:
            secretName: redpanda-tls
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: redpanda
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: linode-block-storage-retain
        resources:
          requests:
            storage: 100Gi
