apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: observability-hub
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: federated-observability
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
      protocol: TCP
    - name: kafka-tls
      port: 9093
      targetPort: kafka-tls
      protocol: TCP
    - name: rpc
      port: 33145
      targetPort: rpc
      protocol: TCP
    - name: admin
      port: 9644
      targetPort: admin
      protocol: TCP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redpanda
  namespace: observability-hub
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: federated-observability
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redpanda
