apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-topics
  namespace: observability-hub
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/part-of: federated-observability
  annotations:
    description: "Topic definitions - apply via rpk or init container"
data:
  create-topics.sh: |
    #!/bin/bash
    set -e

    RPK="rpk --brokers redpanda-0.redpanda.observability-hub.svc.cluster.local:9092"

    # Metrics topic - 12 partitions, 7 day retention
    $RPK topic create otlp.metrics \
      --partitions 12 \
      --replicas 3 \
      --topic-config retention.ms=604800000 \
      --topic-config cleanup.policy=delete \
      --topic-config compression.type=zstd \
      --topic-config max.message.bytes=10485760 || true

    # Logs topic - 12 partitions, 7 day retention
    $RPK topic create otlp.logs \
      --partitions 12 \
      --replicas 3 \
      --topic-config retention.ms=604800000 \
      --topic-config cleanup.policy=delete \
      --topic-config compression.type=zstd \
      --topic-config max.message.bytes=10485760 || true

    # Traces topic - 12 partitions, 3 day retention
    $RPK topic create otlp.traces \
      --partitions 12 \
      --replicas 3 \
      --topic-config retention.ms=259200000 \
      --topic-config cleanup.policy=delete \
      --topic-config compression.type=zstd \
      --topic-config max.message.bytes=10485760 || true

    # Dead letter queue - 6 partitions, 30 day retention
    $RPK topic create otlp.dlq \
      --partitions 6 \
      --replicas 3 \
      --topic-config retention.ms=2592000000 \
      --topic-config cleanup.policy=delete \
      --topic-config compression.type=zstd || true

    echo "All topics created successfully"
    $RPK topic list
---
apiVersion: batch/v1
kind: Job
metadata:
  name: redpanda-create-topics
  namespace: observability-hub
  labels:
    app.kubernetes.io/name: redpanda
    app.kubernetes.io/component: topic-init
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: rpk
          image: docker.redpanda.com/redpandadata/redpanda:v24.1.1
          command: ["/bin/bash", "/scripts/create-topics.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: redpanda-topics
            defaultMode: 0755
