apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoria-metrics
  namespace: observability-hub
  labels:
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/component: metrics-store
    app.kubernetes.io/part-of: federated-observability
spec:
  serviceName: victoria-metrics
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: victoria-metrics
        app.kubernetes.io/component: metrics-store
    spec:
      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics:v1.99.0
          args:
            - -storageDataPath=/data
            - -retentionPeriod=30d
            - -httpListenAddr=:8428
            - -promscrape.config=/config/scrape.yaml
            - -search.maxConcurrentRequests=32
            - -search.maxUniqueTimeseries=1000000
          ports:
            - name: http
              containerPort: 8428
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: victoria-metrics-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: linode-block-storage-retain
        resources:
          requests:
            storage: 50Gi
