apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: client-ca
  namespace: observability-hub
spec:
  vaultAuthRef: vso-auth
  mount: observability
  type: kv-v2
  path: mtls-ca
  refreshAfter: 60s
  destination:
    name: client-ca
    create: true
    overwrite: true
    labels:
      app.kubernetes.io/part-of: federated-observability
      app.kubernetes.io/managed-by: vault-secrets-operator
    transformation:
      excludeRaw: true
      excludes:
        - ca_crt
        - ca_key
      templates:
        ca.crt:
          text: '{{ get .Secrets "ca_crt" }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: otel-gateway
