apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bert-inference-hpa
  namespace: bert-inference
  labels:
    app: bert-inference
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bert-inference
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 1
          periodSeconds: 30
      selectPolicy: Max
