---
# External Secrets - Sync Vault secrets to Kubernetes
# These ExternalSecrets pull credentials from Vault and create K8s Secrets
#
# Usage: kubectl apply -f external-secrets.yaml
#
---
# TLS Certificate for Grafana (from Vault -> K8s Secret)
# Note: cert-manager already manages this via Let's Encrypt,
# but this shows how to sync TLS certs from Vault if needed
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-tls-vault
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-observability
  target:
    name: grafana-tls-from-vault
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: tls/grafana
        property: tls.crt
        decodingStrategy: Base64
    - secretKey: tls.key
      remoteRef:
        key: tls/grafana
        property: tls.key
        decodingStrategy: Base64
---
# Splunk HEC Token
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: splunk-credentials
  namespace: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-observability
  target:
    name: splunk-credentials
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: destinations/splunk
        property: token
    - secretKey: endpoint
      remoteRef:
        key: destinations/splunk
        property: endpoint
---
# Datadog API Key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-credentials
  namespace: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-observability
  target:
    name: datadog-credentials
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: destinations/datadog
        property: api_key
    - secretKey: site
      remoteRef:
        key: destinations/datadog
        property: site
---
# Customer OTLP Endpoint Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otlp-credentials
  namespace: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-observability
  target:
    name: otlp-credentials
    creationPolicy: Owner
  data:
    - secretKey: endpoint
      remoteRef:
        key: destinations/otlp
        property: endpoint
    - secretKey: auth_header
      remoteRef:
        key: destinations/otlp
        property: auth_header
