---
# External Secrets Operator - Vault SecretStore
# This connects ESO to the Vault server for secret synchronization
#
# Prerequisites:
#   kubectl apply -f https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml
#   helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace
#
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
stringData:
  token: "hvs.zCLBrYIVatCMCXTvR0G5D0uQ"  # Replace with service account token in production
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-observability
spec:
  provider:
    vault:
      server: "http://172.236.105.15:8200"
      path: "observability"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: external-secrets
          key: token
